### ISSUE TITLE
Overwrite text

### ISSUE THREAD

**Issue by ibotty** [infinum/cookies_eu#62]
Thank you for developing this gem!

How can I overwrite the text to display?

**Comment by gabskoro** [comment]
Tnx :) Just open your `.yml` file in the locales folder and override it by adding:

```yml
en:
  cookies_eu:
    cookies_text: YOUR_TEXT
    learn_more: YOUR_TEXT
    ok: YOUR_TEXT
```

Will add this to the readme :)
